title: "MJA Dev Blog"
description: "A simple Jekyll blog for development notes and updates."
author: "mjadev360"
url: "https://mjadev360.github.io"
baseurl: "/blog"
theme: minima
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
